# Deliver Cube to Scale around back of switch


path = "R_SC_O_C1D_D"
wait1 = 0.9
wait2 = 0.25
direction1 = 0.0
distance1 = 420_000
azimuth1 = 0.0
direction2 = 0.0
distance2 = 5_000
azimuth2 = -180.0
