#            ____   _____        _______ ____    _   _ ____
#           |  _ \ / _ \ \      / / ____|  _ \  | | | |  _ \
#           | |_) | | | \ \ /\ / /|  _| | |_) | | | | | |_) |
#           |  __/| |_| |\ V  V / | |___|  _ <  | |_| |  __/
#           |_|    \___/  \_/\_/  |_____|_| \_\  \___/|_|
#  ____        __             _ _     ____       _   _   _
# |  _ \  ___ / _| __ _ _   _| | |_  / ___|  ___| |_| |_(_)_ __   __ _ ___
# | | | |/ _ \ |_ / _` | | | | | __| \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |_| |  __/  _| (_| | |_| | | |_   ___) |  __/ |_| |_| | | | | (_| \__ \
# |____/ \___|_|  \__,_|\__,_|_|\__| |____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                                |___/
# These settings are used if not overridden in ~lvuser/powerup.toml on roboRIO

[POWERUP]
description   = "Stryke Force 2018 POWER UP"

[POWERUP.VISION]
  brightness = 50
  exposure   = 40
  intakeCameraPath = "/dev/v4l/by-path/platform-ci_hdrc.0-usb-0:1.2:1.0-video-index0"
  liftCameraPath   = "/dev/v4l/by-path/platform-ci_hdrc.0-usb-0:1.1:1.0-video-index0"
  enableCamera  = true

[POWERUP.PATH]
  p_azimuth        = -0.004
  p_distance       = 2e-6
  f_acceleration   = 0.0
  ticksPerInchRedLeft   = 2273 # carpet-x pull test
  ticksPerInchRedRight  = 2273 # carpet-x pull test
  ticksPerInchBlueLeft  = 2273
  ticksPerInchBlueRight = 2273

[POWERUP.AZIMUTH]
  p = 0.013
  i = 0.0
  d = 0.0
  tolerance = 1.0
  outputMax = 0.3
  test = false

[POWERUP.JOYSTICK]
  deadband    = 0.10
  driveExpo   = 0.5
  azimuthExpo = 0.2
  rateLimit   = 0.04

[POWERUP.CLIMBER]
  upFastOutput  = 1.0
  upSlowOutput  = 0.35
  stopOutput    = 0.0
  unwindOutput  = -0.15
  releaseOutput = 0.15

  slowDownPosition = 37_700

[POWERUP.INTAKE]
  normalCurrentLimit = 12  # when changing, also change in thirdcoast.toml
  holdCurrentLimit   = 2

  # practice
  lidarSlope  = 1.0
  lidarOffset = -19.4

  # comp
#  lidarSlope  = 1.0
#  lidarOffset = 0.0

  # velocities
  loadVelocity       = -10_000
  holdVelocity       = -1500
  fastEjectVelocity  =  10_000
  scaleEjectVelocity =  3000
  slowEjectVelocity  =  1000 #2000
  switchEjectVelocity = 3000

  # release positions
  zeroPosition = 2048
  openPosition = 2500

  # release servo positions
  leftServoDefault = 0.6
  leftServoClamp = 0.8
  leftServoOpen = 0.0
  rightServoDefault = 0.4
  rightServoClamp = 0.2
  rightServoOpen = 1.0

[POWERUP.LIFT]
  timeout      = 0.5
  upOutput     = 0.25
  downOutput   = -0.2
  stopOutput   = 0.0
  closeEnough  = 250
  jogIncrement = 1400

  # positions
  scaleLowPosition     = 13_824
  scaleMidPosition     = 15_700
  scaleHighPosition    = 18_000
  stowPosition         = 0
  portalPosition       = 5200
  downVelocityShiftPos = 7000

  # velocities
  upAccel          = 6000
  upVelocity       = 2500
  downSlowAccel    = 7500
  downSlowVelocity = 3000
  downFastAccel    = 7500
  downFastVelocity = 3000

[POWERUP.SHOULDER]
  upOutput       = 0.4
  downOutput     = -0.4
  stopOutput     = 0.0
  closeEnough    = 500

  # positions
  limitSwitchZeroPosition = 9394
  # practice absEncoderZeroPosition  = 1127
  absEncoderZeroPosition  = 1900
  tightStowPosition       = 8666
  stowPosition            = 7500
  intakePosition          = -166
  launchSwitchPosition    = 6666
  launchScalePosition     = 4166

[POWERUP.EXTENDER]
  leftUpPosition     = 0.41
  leftDownPosition   = 0.2
  rightDownPosition  = 0.8
  rightUpPosition    = 0.57

[POWERUP.WHEEL]
  ticksPerTooth = 108
  nominalZero   = [1973, 1995, 2045, 2011]

[POWERUP.SMARTDASHBOARD]
  enablePit  = true
  enableTest = true
  enableGame = true
