#            ____   _____        _______ ____    _   _ ____
#           |  _ \ / _ \ \      / / ____|  _ \  | | | |  _ \
#           | |_) | | | \ \ /\ / /|  _| | |_) | | | | | |_) |
#           |  __/| |_| |\ V  V / | |___|  _ <  | |_| |  __/
#           |_|    \___/  \_/\_/  |_____|_| \_\  \___/|_|
#  ____        __             _ _     ____       _   _   _
# |  _ \  ___ / _| __ _ _   _| | |_  / ___|  ___| |_| |_(_)_ __   __ _ ___
# | | | |/ _ \ |_ / _` | | | | | __| \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |_| |  __/  _| (_| | |_| | | |_   ___) |  __/ |_| |_| | | | | (_| \__ \
# |____/ \___|_|  \__,_|\__,_|_|\__| |____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                                |___/
# These settings are used if not overridden in ~lvuser/powerup.toml on roboRIO

[POWERUP]
description = "Stryke Force 2018 POWER UP"
isolatedTestMode = false

[POWERUP.JOYSTICK]
  deadband    = 0.05
  driveExpo   = 0.5
  azimuthExpo = 0.2
  rateLimit   = 0.04

[POWERUP.CLIMBER]
  upOutput   = 1.0
  stopOutput = 0.1

[POWERUP.FLIPPER]
  upOutput     = 0.5
  downOutput   = -0.2
  upPosition   = 1000
  downPosition = 200

[POWERUP.INTAKE]
  loadOutput  = -1.0
  holdOutput  = -1.0
  ejectOutput = 0.8

[POWERUP.LIFT]
  upOutput     = 0.1
  downOutput   = -0.05
  stopOutput   = 0.0
  closeEnough  = 50
  jogIncrement = 1400

  # scale positions
  scaleLow     = 9100
  scaleMedium  = 13_300
  scaleHigh    = 17_100

[POWERUP.SHOULDER]
  upOutput     = 0.2
  downOutput   = -0.2
  stopOutput   = 0.0
  closeEnough  = 50
  zeroPosition = 6750
  jogIncrement = 300

  # positions
  intakePosition = -100

##
## Paths
##

  [PATHS.LEFT]
  waypoints = [
    {x = 0.0, y = 0.0, angle = 0.0},
    {x = 8.0, y = -0.2, angle = 0.0},
    {x = 10.0, y = -0.4, angle = 0.0},
    {x = 11.5, y = -0.7, angle = 0.0},
    {x = 12.0, y = -1.5, angle = -90.0},
  ]
  fit              = "HERMITE_CUBIC"
  sample_count     = 100_000
  dt               = 0.05  # sec
  max_velocity     = 1.7   # m/sec
  max_acceleration = 2.0   # m/sec/sec
  max_jerk         = 60.0  # m/sec/sec/sec
  p_azimuth        = -0.004

  [PATHS.CENTERLEFT]
  waypoints = [
    {x = 0.0, y = 0.0, angle = 35.0},
    {x = 3.75, y = 2.8, angle = 40.0},
    {x = 7.5, y = 5.16, angle = 0.0},
  ]

  fit              = "HERMITE_CUBIC"
  sample_count     = 100_000
  dt               = 0.05  # sec
  max_velocity     = 1.7   # m/sec
  max_acceleration = 2.0   # m/sec/sec
  max_jerk         = 60.0  # m/sec/sec/sec
  p_azimuth        = -0.004

  [PATHS.CENTERRIGHT]
  waypoints = [
    {x = 0.0, y = 0.0, angle = -35.0},
    {x = 3.75, y = -2.8, angle = -35.0},
    {x = 7.8, y = -3.5, angle = 0.0},
  ]
  fit              = "HERMITE_CUBIC"
  sample_count     = 100_000
  dt               = 0.05  # sec
  max_velocity     = 1.7   # m/sec
  max_acceleration = 2.0   # m/sec/sec
  max_jerk         = 60.0  # m/sec/sec/sec
  p_azimuth        = -0.004

  [PATHS.CENTERRIGHTEXCHANGE]

  waypoints = [
    {x = 0.0, y = 0.0, angle = -35.0},
    {x = 7.5, y = -3.7, angle = 0.0},
    {x = 6.0, y = -2.5, angle = -90.0},
    {x = 6.0, y = -1.0, angle = -90.0},
    {x = 5.0, y = -1.7, angle = -180.0},
    {x = 0.0, y = 1.5, angle = -180.0}

  ]
  fit              = "HERMITE_CUBIC"
  sample_count     = 100_000
  dt               = 0.05  # sec
  max_velocity     = 1.7   # m/sec
  max_acceleration = 2.0   # m/sec/sec
  max_jerk         = 60.0  # m/sec/sec/sec
  p_azimuth        = -0.004
