waypoints = [
  {x = 0.0, y = 0.0, angle = -35.0},
  {x = 3.75, y = -2.8, angle = -35.0},
  {x = 7.8, y = -3.5, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 100_000
dt               = 0.05  # sec
max_velocity     = 1.7   # m/sec
max_acceleration = 2.0   # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec
