# right opposite scale

waypoints = [
  {x = 0.0, y = 0.0, angle = 0.0},
  {x = 2.6, y = -0.70, angle = 0.0},
  {x = 3.92, y = -0.70, angle = 0.0},
  {x = 5.3, y = 1.2, angle = 90.0},
  {x = 5.3, y = 4.00, angle = 90.0},
  {x = 6.6, y = 5.54, angle = 0.0},
]

fit              = "HERMITE_CUBIC"
sample_count     = 20_000
dt               = 0.050    # sec
max_velocity     = 3.0   # m/sec
max_acceleration = 2.5  # m/sec/sec
max_jerk         = 60.0  # m/sec/sec/sec